### ISSUE TITLE
Replace optparse with argparse

### ISSUE THREAD

**Issue by Toilal** [Tigge/Garmin-Forerunner-610-Extractor#115]
[optparse](https://docs.python.org/2/library/optparse.html) is deprecated and should be replaced with [argparse](https://docs.python.org/2/library/argparse.html). I did this already in [another project](https://github.com/wackou/guessit/commit/665c5d598d211de7ebc4efb9118235eab246f329), it's quite straight-forward.

For python<2.7, module sources are available on pip (`pip install argparse`).

I can make a PR as soon as #112 is merged.

**Comment by Tigge** [comment]
Yeah, `argparse` is also a much nicer to use than `optparse` but I kept using `optparse` to cater to the pre 2.7 population. A year or so have passed since then and if it is also available from pip I'm all for it!

**Comment by Toilal** [comment]
Ok @Tigge , PR is ready, i just wait the merge of python3 to open it.
