### ISSUE TITLE
Runs don't get flagged as downloaded (seemingly)

### ISSUE THREAD

**Issue by superm1** [Tigge/Garmin-Forerunner-610-Extractor#58]
I have two computers that I have used this project with along with my 310xt successfully.  Unfortunately I've noticed that if I download a run on one computer and then initiate a download of a future run with a different computer the second computer downloads both runs.

If I download from just the first one twice then just one run is downloaded the second time.  It's almost as though the run doesn't get marked as downloaded on the watch.

Coming from an older 405 (and a different project: python-ant-downloader) this wasn't an issue for me, it seemed runs were marked as downloaded.

**Comment by mgr01** [comment]
I'll do it.
